theme: minimal-mistakes-jekyll
title: 'Iacopo Masi, Ph.D.'
description: 'Associate Professor at the University of Rome, La Sapienza; Adjunct Research Assistant Professor at the University of Southern California'
logo: /imgs/sapienza_usc_logo.png
show_downloads: false
gems: 
  - jemoji
