theme: jekyll-theme-minimal
title: 'Iacopo Masi, Ph.D.'
description: 'Associate Professor at the University of Rome, La Sapienza; Adjunct Research Assistant Professor at the University of Southern California'
logo: /imgs/usc.png
show_downloads: false
