theme: jekyll-theme-minimal
title: 'Iacopo Masi, Ph.D.'
description: '<p style="text-align:left">Associate Professor at the University of Rome, La Sapienza @ Computer Science Department</p>'
logo: /imgs/logo.png
show_downloads: false
