theme: jekyll-theme-minimal
title: 'Iacopo Masi, Ph.D.'
description: '<p style="text-align:left">Associate Professor at the University of Rome, La Sapienza; Adjunct Research Assistant Professor at the University of Southern California</p>'
logo: /imgs/sapienza_usc_logo.png
show_downloads: false
