theme: jekyll-theme-minimal
title: 'Iacopo Masi'
description: 'Research Assistant Professor at Computer Science Department, USC Viterbi School of Engineering; Research Computer Scientist at the USC Information Sciences Institute'
logo: /imgs/usc.png
show_downloads: false
